<?php

function webwinkelkeur_script_menu() {
    $items['admin/config/webwinkelkeur/script'] = array(
        'title' => 'Script settings',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('webwinkelkeur_script_settings'),
        'access arguments' => array('administer site configuration'),
    );
    return $items;
}

function webwinkelkeur_script_settings() {
    $form = array();

    $form['script'] = array(
        '#type' => 'fieldset',
        '#title' => t('Script'),
    );
    $form['script']['tooltip_enabled'] = array(
        '#type' => 'checkbox',
        '#title' => t('Show tooltips'),
        '#default_value' => variable_get('webwinkelkeur_tooltip', false),
    );
    $form['script']['sidebar_enabled'] = array(
        '#type' => 'checkbox',
        '#title' => t('Show sidebar'),
        '#default_value' => variable_get('webwinkelkeur_sidebar', true),
    );
    $form['sidebar_position_options'] = array(
        '#type' => 'value',
        '#value' => array(t('Left'), t('Right')),
    );
    $form['script']['sidebar_position'] = array(
        '#type' => 'radios',
        '#title' => t('Sidebar side'),
        '#options' => $form['sidebar_position_options']['#value'],
        '#default_value' => variable_get('webwinkelkeur_sidebar_position', 0),
    );
    $form['script']['sidebar_top'] = array(
        '#type' => 'textfield',
        '#title' => t('Sidebar position (in pixels)'),
        '#default_value' => variable_get('webwinkelkeur_sidebar_top', ''),
    );

    $form['#submit'][] = 'webwinkelkeur_script_settings_submit';

    return system_settings_form($form);
}

function webwinkelkeur_script_settings_submit($form, &$form_state) {
    variable_set('webwinkelkeur_tooltip', $form_state['values']['tooltip_enabled']);
    variable_set('webwinkelkeur_sidebar', $form_state['values']['sidebar_enabled']);
    variable_set('webwinkelkeur_sidebar_top', $form_state['values']['sidebar_top']);
    variable_set('webwinkelkeur_sidebar_position', $form_state['values']['sidebar_position']);
}

function webwinkelkeur_script_page_alter(&$page) {
    if(preg_match('|^admin|', $_GET['q']))
        return;

    $shopid = variable_get('webwinkelkeur_shopid', '');
    if(empty($shopid))
        return;

    $sidebar = variable_get('webwinkelkeur_sidebar', false);
    $tooltip = variable_get('webwinkelkeur_tooltip', false);
    if(!$sidebar && !$tooltip)
        return;

    $js_vars = sprintf("_webwinkelkeur_id=%d\n", $shopid)
             . sprintf("_webwinkelkeur_sidebar=%s\n", $sidebar)
             . sprintf("_webwinkelkeur_tooltip=%s\n", $tooltip);

    $voffset  = variable_get('webwinkelkeur_sidebar_top', '');
    if(!empty($voffset))
        $js_vars .= sprintf("_webwinkelkeur_sidebar_top=\"%s\"\n", $voffset);

    $position = variable_get('webwinkelkeur_sidebar_position', 1) ? 'right' : 'left';
    $js_vars .= sprintf('_webwinkelkeur_sidebar_position="%s"', $position);

    drupal_add_js($js_vars, array(
        'type' => 'inline', 'scope' => 'footer'
    ));
    drupal_add_js('http://www.webwinkelkeur.nl/js/sidebar.js', array(
        'type' => 'external', 'scope' => 'footer',
    ));
}

