<?php

function webwinkelkeur_ubercart_menu() {
    $items['admin/config/webwinkelkeur/invites'] = array(
        'title' => 'Ubercart invites settings',
        'description' => 'Changes how invitations are sent to customers.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('webwinkelkeur_invites_settings'),
        'access arguments' => array('administer site configuration'),
        'file' => 'webwinkelkeur.invite.inc',
    );
    return $items;
}

function webwinkelkeur_ubercart_webwinkelkeur_invites() {
    $query = '
        SELECT order_id, primary_email as mail
        FROM {uc_orders}
        WHERE webwinkelkeur_invite_sent = 0
            AND webwinkelkeur_invite_tries < 10
            AND webwinkelkeur_invite_time < :wwk_time
    ';

    return db_query($query, array('wwk_time' => time() - 1800));
}

function webwinkelkeur_ubercart_webwinkelkeur_invites_update($orders) {
    foreach($orders as $order) {
        db_update('uc_orders')
            ->fields(array('webwinkelkeur_invite_time' => time()))
            ->expression('webwinkelkeur_invite_tries', 'webwinkelkeur_invite_tries + 1')
            ->condition('order_id', $order['id'])
            ->execute()
        ;

        if($order['sent'])
            db_update('uc_orders')
                ->fields(array('webwinkelkeur_invite_sent' => 1))
                ->condition('order_id', $order['id'])
                ->execute()
            ;
    }
}

