<?php

function webwinkelkeur_menu() {
    $items['admin/config/webwinkelkeur'] = array(
        'title' => 'WebwinkelKeur',
        'position' => 'left',
        'weight' => -100,
        'page callback' => 'system_admin_menu_block_page',
        'access arguments' => array('access administration pages'),
        'file' => 'system.admin.inc',
        'file path' => drupal_get_path('module', 'system'),
    );
    $items['admin/config/webwinkelkeur/account'] = array(
        'title' => 'Account settings',
        'description' => 'Configures WebwinkelKeur account details.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('webwinkelkeur_account_settings'),
        'access arguments' => array('administer site configuration'),
        'weight' => -1,
    );
    return $items;
}

function webwinkelkeur_account_settings() {
    $form = array();

    $form['account'] = array(
        '#type' => 'fieldset',
        '#title' => t('Account'),
    );
    $form['account']['shopid'] = array(
        '#type' => 'textfield',
        '#title' => t('Webshop ID'),
        '#default_value' => variable_get('webwinkelkeur_shopid', ''),
    );
    $form['account']['apikey'] = array(
        '#type' => 'textfield',
        '#title' => t('Webshop API key'),
        '#default_value' => variable_get('webwinkelkeur_apikey', ''),
    );

    $form['#validate'][] = 'webwinkelkeur_account_settings_validate';
    $form['#submit'][] = 'webwinkelkeur_account_settings_submit';

    return system_settings_form($form);
}

function webwinkelkeur_account_settings_validate($form, &$form_state) {
    if(!preg_match('|^\d*$|', trim($form_state['values']['shopid'])))
        form_set_error('shopid', t('Webshop ID can contain only numbers.'));
}

function webwinkelkeur_account_settings_submit($form, &$form_state) {
    variable_set('webwinkelkeur_shopid', trim($form_state['values']['shopid']));
    variable_set('webwinkelkeur_apikey', trim($form_state['values']['apikey']));
}

function webwinkelkeur_cron() {
    global $language;

    $shopid = variable_get('webwinkelkeur_shopid', '');
    $apikey = variable_get('webwinkelkeur_apikey', '');
    if(empty($shopid) || empty($apikey))
        return;

    foreach(module_implements('webwinkelkeur_invites') as $module) {
        $orders = module_invoke($module, 'webwinkelkeur_invites');

        if($orders->rowCount() == 0)
            continue;

        $invite_type = variable_get('webwinkelkeur_invite_type', 1);
        $invite_delay = (int) variable_get('webwinkelkeur_invite_delay', 0);

        $responses = array();

        foreach($orders as $order) {
            $parameters = array(
                'id'   => $shopid,
                'code' => $apikey
            );
            $post = array(
                'email'     => $order->mail,
                'order'     => $order->order_id,
                'delay'     => $invite_delay,
                'language'      => $language->language,
                'customer_name'  => $order->customer_name,
                'client'        => 'drupal-' . VERSION,
            );

            if($invite_type == 2)
                $post['max_invitations_per_email'] = '1';

            $url = 'https://dashboard.webwinkelkeur.nl/api/1.0/invitations.json?' . http_build_query($parameters);
            $ch = curl_init($url);
            curl_setopt_array($ch, array(
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_POST => true,
                CURLOPT_POSTFIELDS => http_build_query($post),
                CURLOPT_SSL_VERIFYPEER => false
            ));
            $r = curl_exec($ch);
            curl_close($ch);

            $result = @json_decode($r);
            if (is_object($result) && isset ($result->status) && $result->status == 'success') {
                $sent = true;
            } else {
                $sent = false;
                watchdog('webwinkelkeur', "%response<br>\n(%url)", array(
                    '%url' => $url, '%response' => $r
                ));
            }
            $responses[] = array('id' => $order->order_id, 'sent' => $sent);
        }

        $fn = $module . '_webwinkelkeur_invites_update';
        $fn($responses);
    }
}

