<?php

function webwinkelkeur_ubercart_menu() {
    $items['admin/config/webwinkelkeur/invites'] = array(
        'title' => 'Übercart invitation settings',
        'description' => 'Changes how invitations are sent to customers.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('webwinkelkeur_invites_settings'),
        'access arguments' => array('administer site configuration'),
        'file' => 'webwinkelkeur.invite.inc',
    );
    return $items;
}

function webwinkelkeur_ubercart_webwinkelkeur_invites() {
    $query = '
        SELECT *
        FROM {uc_orders}
        WHERE webwinkelkeur_invite_sent = 0
            AND webwinkelkeur_invite_tries < 10
            AND webwinkelkeur_invite_time < :wwk_time
    ';

    if(variable_get('webwinkelkeur_invite_completed_only', true))
        $query .= "AND order_status = 'completed'";

    return db_query($query, array('wwk_time' => time() - 1800));
}

function webwinkelkeur_ubercart_webwinkelkeur_invites_update($orders) {
    foreach($orders as $order) {
        db_update('uc_orders')
            ->fields(array('webwinkelkeur_invite_time' => time()))
            ->expression('webwinkelkeur_invite_tries', 'webwinkelkeur_invite_tries + 1')
            ->condition('order_id', $order['id'])
            ->execute()
        ;

        if($order['sent'])
            db_update('uc_orders')
                ->fields(array('webwinkelkeur_invite_sent' => 1))
                ->condition('order_id', $order['id'])
                ->execute()
            ;
    }
}

function webwinkelkeur_ubercart_webwinkelkeur_get_platform_version() {
    $ubercart_info = system_get_info('module', 'uc_store');
    return 'uc-' . $ubercart_info['version'];
}

function webwinkelkeur_ubercart_webwinkelkeur_get_order_id($order) {
    return $order->order_id;
}

function webwinkelkeur_ubercart_webwinkelkeur_get_order_email($order) {
    return $order->primary_email;
}

function webwinkelkeur_ubercart_webwinkelkeur_get_order_customer_name($order) {
    return $order->billing_first_name . ' ' . $order->billing_last_name;
}

function webwinkelkeur_ubercart_webwinkelkeur_get_order_phone_numbers($order) {
    return array_unique(array_filter(array($order->billing_phone, $order->delivery_phone)));
}

