<?php

function webwinkelkeur_script_menu() {
    $items['admin/config/webwinkelkeur/script'] = array(
        'title' => 'Script settings',
        'description' => 'Presents site ratings to visitors.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('webwinkelkeur_script_settings'),
        'access arguments' => array('administer site configuration'),
    );
    return $items;
}

function webwinkelkeur_script_settings() {
    $form = array();

    $form['script'] = array(
        '#type' => 'fieldset',
        '#title' => t('Script'),
    );
    $form['script']['javascript_enabled'] = array(
        '#type' => 'checkbox',
        '#title' => t('Enable Javascript integration'),
        '#default_value' => variable_get('webwinkelkeur_javascript', false),
        '#description' => t("Use the JavaScript integration to display the sidebar and tooltip on your website. You can configure these features through the <a href='https://dashboard.webwinkelkeur.nl/integration' target='_blank'>WebwinkelKeur Dashboard</a>."),
    );

    $form['#submit'][] = 'webwinkelkeur_script_settings_submit';

    return system_settings_form($form);
}

function webwinkelkeur_script_settings_submit($form, &$form_state) {
    variable_set('webwinkelkeur_javascript', $form_state['values']['javascript_enabled']);
}

function webwinkelkeur_script_page_alter(&$page) {
    if(preg_match('|^admin|', $_GET['q']))
        return;

    $shopid = variable_get('webwinkelkeur_shopid', '');
    if(empty($shopid))
        return;

    $javascript = variable_get('webwinkelkeur_javascript', false);
    if(!$javascript)
        return;

    $js_vars = sprintf("_webwinkelkeur_id=%d;\n", $shopid);

    drupal_add_js($js_vars, array(
        'type' => 'inline', 'scope' => 'footer'
    ));
    drupal_add_js('https://www.webwinkelkeur.nl/js/sidebar.js', array(
        'type' => 'external', 'scope' => 'footer',
    ));
}

